# Generated by Django 5.1.2 on 2024-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderd_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
