# Generated by Django 5.1.2 on 2024-10-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_order_orderd_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_img',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
